### ISSUE TITLE
Small improvements

### ISSUE THREAD

**Issue by kadyb** [ailich/GLCMTextures#21]
Hi Alex, congratulations on releasing the packages on CRAN! I think you can consider these things to improve the user experience:

1. Add `BugReports` field to DESCRIPTION: `BugReports: https://github.com/ailich/GLCMTextures/`
2. Create [pkgdown](https://github.com/r-lib/actions/blob/v2/examples/pkgdown.yaml) website
3. Add CRAN badge to README: `[![CRAN](https://www.r-pkg.org/badges/version/GLCMTextures)](https://cran.r-project.org/package=GLCMTextures)`. And maybe badge with [license](https://shields.io/category/license)?

**Comment by ailich** [comment]
Thanks @kadyb. I've added those suggestions. The equations however aren't rendering properly on [the packagedown website](https://ailich.github.io/GLCMTextures/). Any chance you know how to address that. I remember [adding the option `--webtex` to the Readme so that it'd display properly on github](https://stackoverflow.com/questions/48511527/how-to-display-math-in-an-rmd-file-on-github) however, it seems that [may be causing an issue on the packagedown site](https://github.com/r-lib/pkgdown/issues/1150). Do you have any suggestions. I tried changing the option to `--mathml` but it made no difference.

**Comment by kadyb** [comment]
I changed `--webtex` to `--mathml` and single `$` to double `$$` and this works: https://kadyb.github.io/GLCMTextures/

BTW: I tried to fork this repository on GitHub, but there is the error: `Description cannot be more than 350 characters`. Maybe you should shorten the "About" section?

**Comment by ailich** [comment]
Thanks, I shortened the about section so not the repo can be forked. I'm still having issues rendering the packagedown website even though I made both the [`--mathml`](https://github.com/ailich/GLCMTextures/blob/d11fef7f1bb654fe78432ab03378a265b226f241/README.Rmd#L7) and [`$$` changes](https://github.com/ailich/GLCMTextures/blob/d11fef7f1bb654fe78432ab03378a265b226f241/README.Rmd#L65-L81).

**Comment by ailich** [comment]
I updated `knitr` and `rmarkdown` and now I do get some warnings (e.g. see below), but it renders properly.

[WARNING] Could not convert TeX math \text{GLCM Mean} (\mu) = \sum_{i,j=0}^{N-1} i(P_{i,j}), rendering as TeX
igma^2) = \sum_{i,j=0}^{N-1} P_{i,j}(i-\mu)^2, rendering as TeX
